### ISSUE TITLE
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by AnjumJethi** [deblockt/cucumber-report-annotations-action#25]
I am getting unhandled Promise rejection warning while trying to read the cucumber-report.json file. Please refer to the attached screen shot.
![GitHubActions](https://user-images.githubusercontent.com/25073688/145158109-83aa6ce4-ef6d-4b0f-88d5-d244e613af77.png)

**Comment by deblockt** [comment]
At first view, It seem that your cucumber-report.json don't contains valid json. can you verify the content of cucumber-report.json?

**Comment by deblockt** [comment]
closed due to inactivity
