### ISSUE TITLE
stop a build based on the failed test

### ISSUE THREAD

**Issue by Ajish8** [deblockt/cucumber-report-annotations-action#38]
Hello,

Can i stop/exit a build based on the failed test?

Appreciate your response.

**Comment by deblockt** [comment]
Hi,

I currently not possible. 
This is a new feature to add to this action

**Comment by deblockt** [comment]
You can use the v1.11 https://github.com/deblockt/cucumber-report-annotations-action/releases/tag/v1.11 using the new parameter `number-of-test-error-to-fail-job`

**Comment by Ajish8** [comment]
Thanks for the update i will try it and let you know

**Comment by Ajish8** [comment]
Tried it , it works fine. Thank you !
