### ISSUE TITLE
Feature Request: provide output summary

### ISSUE THREAD

**Issue by PavanMudigondaTR** [deblockt/cucumber-report-annotations-action#41]
Is it possible to provide us output of these 5 variables so we can pass to subsequent steps ?

       const summarySteps = {
            'failed': globalInformation.failedStepsNumber,
            'undefined': globalInformation.undefinedStepsNumber,
            'skipped': globalInformation.skippedStepsNumber,
            'pending': globalInformation.pendingStepNumber,
            'passed': globalInformation.succeedStepsNumber
        };

**Comment by deblockt** [comment]
Hi, sorry for the delay. This feature is available on 1.12 version
