### ISSUE TITLE
Node16

### ISSUE THREAD

**Issue by golinko** [deblockt/cucumber-report-annotations-action#46]
Hi, 

I get the following error while using the action:

The following actions uses node12 which is deprecated and will be forced to run on node16: deblockt/cucumber-report-annotations-action@v1.7. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by deblockt** [comment]
Hi, 

You can test with 1.11 version, this version use node16.
