### ISSUE TITLE
Upgrade Node 16 (EOL) to Node 20 (TLS)

### ISSUE THREAD

**Issue by phirk** [deblockt/cucumber-report-annotations-action#49]
Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases).

Please [upgrade](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) to Node 20:

> Modify your actions to run on Node 20 instead of Node 16. For guidance, refer to the [Actions configuration settings](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions).

**Comment by deblockt** [comment]
Hi, thanks for this PR. 
This issue is resolved on version [1.14](https://github.com/deblockt/cucumber-report-annotations-action/releases/tag/v1.14).
