### ISSUE TITLE
Example of Output Variable Use

### ISSUE THREAD

**Issue by nitinagrawal-dario** [deblockt/cucumber-report-annotations-action#52]
Hi, 

Is there any example or document where we can take a reference to the output variable ${output}_failed_scenarios:? 
I tried but was not able to get the outputs.

Thanks

**Comment by deblockt** [comment]
Hi, 

The name depends of you report json file name. 
If your cucumber file name is `cucumber-report.json`, the variable will be `cucumber-report_failed_scenarios`
