### ISSUE TITLE
I can't get de output from the action

### ISSUE THREAD

**Issue by renato-r-cardoso-alb** [deblockt/cucumber-report-annotations-action#54]
The action can read the json file but when i try to get the output it just don't work, here's how i have it

![output](https://github.com/deblockt/cucumber-report-annotations-action/assets/104996590/c878bc72-56cb-41b9-9b71-239194a9d311)

![output2](https://github.com/deblockt/cucumber-report-annotations-action/assets/104996590/b4ad9433-0b16-4eb4-933a-6c931751c55d)

**Comment by deblockt** [comment]
The output name has been fixed. 
But you should update your ci file, you should use `.outputs` instead of `.output`

**Comment by deblockt** [comment]
close due to inactivity
